# Generated by Django 4.0.4 on 2022-07-23 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=500)),
                ('title', models.CharField(max_length=100)),
                ('switch', models.BooleanField(default=True)),
                ('status', models.BooleanField(default=True)),
                ('webType', models.CharField(choices=[('Type1', 'Type1'), ('Type2', 'Type2')], default=None, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Endpoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Endpoint', models.URLField(max_length=500)),
                ('url', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shopify.website')),
            ],
        ),
    ]
