# Generated by Django 4.0.4 on 2022-07-23 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopify', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Endpoints',
            new_name='Endpoint',
        ),
    ]
