# Generated by Django 4.0.4 on 2022-07-23 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopify', '0002_rename_endpoints_endpoint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='website',
            name='webType',
            field=models.CharField(choices=[(None, None), ('Type1', 'Type1'), ('Type2', 'Type2')], default=None, max_length=20),
        ),
    ]
