# Generated by Django 4.0.4 on 2022-07-23 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopify', '0003_alter_website_webtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='website',
            name='webType',
            field=models.CharField(choices=[('', '-----'), ('Type1', 'Type1'), ('Type2', 'Type2')], default='', max_length=20),
        ),
    ]
