# Generated by Django 4.0.4 on 2022-07-23 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopify', '0004_alter_website_webtype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='endpoint',
            old_name='Endpoint',
            new_name='endpoint',
        ),
    ]
